### PR TITLE
[release-v1.1] [Tests] Modifications to Support Wider Environments

### PR DESCRIPTION
**Pull request by Barakmor1**
**What this PR does / why we need it**:
This is a manual cherry-pick of https://github.com/kubevirt/application-aware-quota/pull/85
it is needed to be manually because e2e test for plugable policies doesn't exist in this branch

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by iholder101** [comment]
> it is needed to be manually because e2e test for plugable policies doesn't exist in this branch

So this is why the [Skip plugable policies test if sidecar label images](https://github.com/kubevirt/application-aware-quota/pull/85/commits/50b1c02b28c23b702554f411e662fe78bf0a4bb9) commit is missing?

**Comment by Barakmor1** [comment]
> > it is needed to be manually because e2e test for plugable policies doesn't exist in this branch
> 
> So this is why the [Skip plugable policies test if sidecar label images](https://github.com/kubevirt/application-aware-quota/pull/85/commits/50b1c02b28c23b702554f411e662fe78bf0a4bb9) commit is missing?

Yes :)

**Pull request merged**
