### PR TITLE
Add requirement for release tool for safe publishing

### PR DESCRIPTION
**Pull request by Barakmor1**
**What this PR does / why we need it**:
The current process for creating a Z-stream release for AAQ requires us to force push a new tag.

This approach is not safe, as it requires manual push to the AAQ repository and can cause issues like the one mentioned [here](https://github.com/kubevirt/application-aware-quota/pull/51#issuecomment-2071948516).

To avoid this, we should align with the `kubevirt/kubevirt` project and utilize [the release tool](https://github.com/kubevirt/kubevirt/blob/main/docs/release-procedure.md#creating-new-patch-releases).
This PR adds a requirement script to use the release tool.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Barakmor1** [comment]
FYI @fabiand @awels

**Comment by vladikr** [comment]
Nice! 

/approve
/lgtm

**Pull request merged**
